### ISSUE TITLE
Heap corruption: SerialQueue

### ISSUE THREAD

**Issue by vlazdra** [onevcat/Kingfisher#1289]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [x] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

### Issue Description
Based on the information provided through the crash report it seams that when loading images, a heap corruption occurs.
Not sure how to reproduce it, since it's happening only in production.

#### Reproduce
Can't manually reproduce in the app, but will attach the stack trace:

#### Stack trace
- Crashed: com.onevcat.Kingfisher.ImageProgressive.SerialQueue
- 0  libobjc.A.dylib                0x1943d7bf0 objc_retain + 16
- 1  My App                       0x10337a9b4 specialized getAssociatedObject<A>(_:_:) + 30 (Runtime.swift:30)
- 2  My App                       0x103361e3c KingfisherWrapper<A>.taskIdentifier.getter + 303 (ImageView+Kingfisher.swift:303)
- 3  My App                       0x10336503c partial apply for closure #1 in closure #2 in KingfisherWrapper<A>.setImage(with:placeholder:options:progressBlock:completionHandler:) + 119 (ImageView+Kingfisher.swift:119)
- 4  My App                       0x10335a068 closure #1 in ImageProgressiveProvider.update(data:with:) + 93 (ImageProgressive.swift:93)
- 5  My App                       0x10335f5c8 partial apply for closure #1 in closure #2 in ImageProgressiveSerialQueue.add(minimum:closure:) (<compiler-generated>)
- 6  My App                       0x102ef9254 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
- 7  libdispatch.dylib              0x194bd37f4 _dispatch_block_async_invoke2 + 104
- 8  libdispatch.dylib              0x194c257d4 _dispatch_client_callout + 16
- 9  libdispatch.dylib              0x194bce324 _dispatch_lane_serial_drain$VARIANT$mp + 592
- 10 libdispatch.dylib              0x194bcee40 _dispatch_lane_invoke$VARIANT$mp + 428
- 11 libdispatch.dylib              0x194bd74ac _dispatch_workloop_worker_thread + 596
- 12 libsystem_pthread.dylib        0x194e06114 _pthread_wqthread + 304
- 13 libsystem_pthread.dylib        0

x194e08cd4 start_wqthread + 4

#### Note
Also if it's worth noting that the crash only occurs on iOS 12.

**Comment by onevcat** [comment]
Maybe related to #1276 

Should be already fixed in version 5.8.0.

**Comment by vlazdra** [comment]
I'm not going to open another ticket in hope that you see this comment, but the issue i still present in the latest version of 5.8.1.

- Crashed: com.onevcat.Kingfisher.ImageProgressive.SerialQueue
- 0  libobjc.A.dylib                0x19c9d7e30 objc_retain + 16
- 1  MyApp                       0x100b3457c KingfisherWrapper<A>.taskIdentifier.getter + 304 (ImageView+Kingfisher.swift:304)
- 2 MyApp                       0x100b37940 partial apply for closure #1 in closure #2 in KingfisherWrapper<A>.setImage(with:placeholder:options:progressBlock:completionHandler:) + 120 (ImageView+Kingfisher.swift:120)
- 3  MyApp                       0x100b2c6b0 closure #1 in ImageProgressiveProvider.update(data:with:) + 93 (ImageProgressive.swift:93)
- 4  MyApp                       0x100b31ca0 partial apply for closure #1 in closure #2 in ImageProgressiveSerialQueue.add(minimum:closure:) (<compiler-generated>)
- 5  MyApp                       0x1006cbb1c thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
- 6  libdispatch.dylib              0x19d1d5fac <redacted> + 144
- 7  libdispatch.dylib              0x19d1c9888 <redacted> + 20
- 8  libdispatch.dylib              0x19d1d0dd4 <redacted> + 552
- 9  libdispatch.dylib              0x19d1d1918 <redacted> + 364
- 10 libdispatch.dylib              0x19d1d9cc0 <redacted> + 588
- 11 libsystem_pthread.dylib        0x19d3c5a98 _pthread_wqthread + 308
- 12 libsystem_pthread.dylib        0x19d3cbdc4 start_wqthread + 4

**Comment by onevcat** [comment]
OK. Let's reopen it and have another look!

**Comment by onevcat** [comment]
Do you have any reproducible sample or suspicious use case? It seems that you are loading some progressive JPEG?

**Comment by vlazdra** [comment]
I am using a third party system to load the images in my app.
That system has an ability to reformat the images, since the original images are a little big and .png and I get .jpeg.

I use the ImageProgressive like this:
`options.append(.progressiveJPEG(ImageProgressive(isBlur: false, isFastestScan: true, scanInterval: 0.1)))`

Here are a couple of images that I load in the app. Also might be worth nothing, we load a lot of them at the same time (technical issues in the app are preventing us to optimize that at the moment).

https://images.ctfassets.net/avx85g85supt/6UzUwrtOtUMCyIvfWBp3I4/aaa40fa32509c65d120ec439e75972d0/Juke_tiles_station_Radio10.png?f=center&fit=fill&w=210&h=210&q=90&fm=jpg

**Comment by vlazdra** [comment]
Will close since no longer relative.
Thanks for the assistance.
